# This is the refactored TOML baseline observatory configuration in SI units

description = "STP Spacecraft Baseline Configuration"

[pointing]
jitter_rms = '10e-3arcsecond'
#field_of_regard_min = ''
#field_of_regard_max = ''
# EDIT: Nick Schragal - Replacing fixed field of regard for individual fields of
#                       regard for Sun, Moon, Earth, and small bodies. Assuming same
#                       solar field of regard as Roman, assuming keep-out of 
#                       10 degrees for Moon and Earth for now, assuming no keep-out 
#                       necessary for what EXOSIMS defines as small bodies.
#                       Roman field of regard: https://roman.gsfc.nasa.gov/science/WFI_technical.html
field_of_regard_sun = ["54deg", "126deg"]
field_of_regard_moon = ["10deg", "180deg"]
field_of_regard_earth = ["10deg", "180deg"]
field_of_regard_small_bodies = ["0deg", "180deg"]

[motion]
slew_settle_time_small = "5minutes" # from L3-7009
slew_settle_time_large = "90minutes" # from transient response budget (TBR)
slew_avg_speed = "0.44 degree/second" # estimate from JDP, does not include settling

[acquisition]
offset_motion_time_fine = "30seconds" # TBR from mission lifetime budget
offset_motion_time_coarse = "120seconds" # TBR from mission lifetime budget
offset_measure_time_fine = "10seconds" # TBR from mission lifetime budget
offset_measure_time_coarse = "60seconds" # TBR from mission lifetime budget

[general]
mission_length = "3years" # from L0-0009
