# This is the refactored TOML baseline observatory configuration in SI units

description = "Pearl Spacecraft Baseline Configuration"

[pointing]
jitter_rms = '10e-3arcsecond'
field_of_regard_min = ''
field_of_regard_max = ''

[motion]
slew_settle_time_small = "5minutes" # from L3-7009
slew_settle_time_large = "90minutes" # from transient response budget (TBR)
slew_avg_speed = "0.44 degree/second" # estimate from JDP, does not include settling

[acquisition]
offset_motion_time_fine = "30seconds"
offset_motion_time_coarse = "120seconds"
offset_measure_time_fine = "10seconds"
offset_measure_time_coarse = "60seconds"

[general]
mission_length = "3years"
