# This is a TOML baseline observatory configuration in SI units

title = "Observatory Baseline Configuration"

[general] #---------------------------------------------------------------------
f_number = 15.0 # [unitless] (derived from Zemax by Heejoo)
f_eff = "96.3m" # effective focal length at center of FoV (derived from Zemax by Heejoo)
version = 'TMA_Mark_12F' #Daewook Kim's Space Coronagraph Optical Team Design
field_bias = '0.17degree' #FIXME- what is this? where does it come from? Who uses it?
design_wavelength = '633.0nm' # Must verify that the optical design uses this.            

[optics] #---------------------------------------------------------------------           

[optics.m1]
aper_clear_OD = '6.42m' # astronomically polished clear aperture 
aper_clear_ID = '1.38m' # astronomical polished inner diameter
opd_map = "M1_map.fits" # created using psd_utils from surf_rms, psd_b, and psd_c     
opd_map_goal = "M1_goal_map.fits" # created using psd_utils from surf_rms_goal, psd_b, and psd_c     
surf_rms = '21e-9m' # L4-FOA-M1-1003 - spec from STP M1 Specification (stp202401_0003)
surf_rms_goal = '9.4e-9m' # stretch goal from STP M1 Specification (stp202401_0003)
psd_b = 0.1 # cycles/m
psd_c = 2.8 # power law exponent
temp_nominal = '20Celsius'  # Trade study XYZ and ConOps
temp_nominal_delta = '1Kelvin' # L3-5013 - +/- value about nominal
temp_stability = '0.01Kelvin/hour' # L3-5015 - FIXME - issue with spec?
coating_refl = "NIST_1st_surface_Al.csv"  # NIST reference curve for aged bare aluminum reflectivity
coating_refl_rms = 0.02

[optics.m2]
aper_clear_OD = '0.760m' # astronomically polished clear aperture 
aper_clear_ID = '0.0m' # astronomical polished inner diameter
opd_map = "M2_map.fits" # created using psd_utils from surf_rms, psd_b, and psd_c     
surf_rms = '8e-9m' # L4-FOA-M2-1003
psd_b = 0.1 # cycles/m; L4-FOA-M2-1004
psd_c = 2.8 # power law exponent; L4-FOA-M2-1004
temp_nominal = '-35Celsius' # CBE
temp_nominal_delta = '3Kelvin' # L4-FOA-M2-0007 - remains TBR - +/- value about nominal
temp_stability = '1Kelvin/hour' # LL4-FOA-M2-0003- no value set in requirement - value is a WAG
coating_refl = "NIST_1st_surface_Al.csv" # NIST reference curve for aged bare aluminum reflectivity
coating_refl_rms = 0.005

baffle_OD = '1.38m' # CBE of diameter of secondary baffle obscuration
support_width = '0.15m' # CBE for secondary support baffle width
n_supports = 3 # CBE for number of spider legs 

[optics.m3]
aper_clear_w = '0.568m' # astronomically polished width
aper_clear_h = '0.36m' # astronomical polished height
opd_map = "M3_map.fits" # created using psd_utils from surf_rms, psd_b, and psd_c     
surf_rms = '8e-9m' # - from esc design guide
psd_b = 10 # [cycles/m] - from esc design guide
psd_c = 2.65 # power law exponent -from esc design guide
temp_nominal = '10Celsius' # CBE
temp_nominal_delta = '10Kelvin' # WAG 
temp_stability = '0.05Kelvin/hour' # WAG
coating_refl = "NIST_1st_surface_Al.csv" # NIST reference curve for aged bare aluminum reflectivity
coating_refl_rms = 0.005

[optics.m4]
aper_clear_OD = '0.1m' # astronomically polished clear aperture
aper_clear_ID = '0.0m' # astronomical polished inner diameter
opd_map = "M4_map.fits" # created using psd_utils from surf_rms, psd_b, and psd_c     
surf_rms = '5e-9m' # - from esc design guide
psd_b = 10 # [cycles/m] - from esc design guide
psd_c = 2.65 # power law exponent -from esc design guide
temp_nominal = '1Celsius' # CBE
temp_nominal_delta = '20Kelvin' # CBE 
temp_stability = '0.05Kelvin/hour' # WAG
coating_refl = "NIST_1st_surface_Al.csv" # NIST reference curve for aged bare aluminum reflectivity
coating_refl_rms = 0.005
