# Instrumental parameters ==============================

[spectrograph.mirror]
diameter_ext = 6.5         # Primary mirror external diameter [m]
diameter_int = 1.3         # Primary mirror internal diameter [m]
temperature = 288          # Mirror temperature [K] (0 for none)
emissivity = 0.1           # Mirror emissivity

# NOT USED
# [spectrograph.camera]
# acceptance = 0.6           # Camera acceptance [rad]
# speed = 32                 # Camera speed (f-number)

[spectrograph]
name = "NACRE (baseline)"
spectral_range = [4000, 17000]  # Wavelength domain [Å]
# spectral_resolution and dispersion_law are mutually exclusive
#spectral_resolution = 100   # Constant 2-px resolving power (log sampling)
dispersion_law = "optical_designs/telescope+ifs/dispersion_offner.ecsv"  # Dispersion law ECSV file
                                           # (wavelength, offset [px])
                                           # (should be consistent w/ px_size)
dispersion_scale = 1.3                     # Dispersion law scaling
spectral_sigma = 0.9        # Chromatic (∝ λ) cross-dispersion PSF [px] at 1 µm
xdisp_sigma = 0.3           # Achromatic cross-dispersion PSF [px]
spatial_sigma = 0.030       # Chromatic (∝ λ) spatial PSF on MLA [arcsec] at 1 µm
guiding_sigma = 0.010       # Achromatic guiding/jitter/aberrations on MLA [arcsec]
spatial_scale = 0.040       # MLA sampling (spaxel scale) [arcsec/spx]
#spatial_shape = [10, 11]    # MLA shape (ny, nx) [spx]
#spatial_scale_insigma = 1.0       # MLA sampling [spatial_sigma/spx]
spatial_shape_insigma = [20, 21]  # MLA shape (ny, nx) [spatial_sigma]
# Throughput: either a constant or an ECSV file
#throughput = 0.7            # Total throughput (but QE) [% ph]
throughput = "optical_designs/telescope+ifs/throughput_baseline.ecsv"  # Total throughput (but QE) (wavelength, throughput)
# mla_fill_factor = 0.9: not implemented (to be incorporated in throughput)
# scattered light: not implemented

[detector]
name = "H4RG17"
# QE: either a constant or an ECSV file
#QE = 0.8                   # Constant quantum efficiency [e-/ph]
QE = "sensors/H4RG17/H4RG17.ecsv"         # Quantum efficiency ECSV file [e-/ph] (wavelength, qe)
gain = 1.0                 # Gain [ADU/e-]
saturation = 65635         # Saturation limit [ADU] (0 for none)
readout_noise = 10.0       # Read-out noise per frame [e-]
tframe = 2.830             # Single frame (read) time [s]
px_size = 10.0             # Pixel physical size [µm]
                           # (should be consistent w/ dispersion_law)
dark = 1e-2                # Dark current [e-/s/px]
# M(ULTI)ACC(UM) modes (using Rausher+07 NMD notations):
# N=#groups, M=#frames/group, D=#drops between groups
# M should be a power of 2 for electronics
# N>1, M=1, D=0: Up-The-Ramp
# N=2, M=1: Correlated Double Sampling (aka Fowler)
# N=2, M>1: Multiple CDS (aka Fowler-M)
readout_mode = [16, 16, 0]  # (N * (M + D) - D) = 256 frames, exptime = 12'05''
variance_model = "Rauscher+07"  # Variance model (Kubik20 or Rauscher+07)

# NOT IMPLEMENTED: dark current as function of detector temperature
# cutoff = 1.7         # Cut-off wavelength [µm] (for dark current)
# temperature = 0      # Temperature [K] (for dark current, 0 for none)

# Deta-reduction parameters ==============================

[extraction]
# All extractions are optimal (i.e. profile weighted least-squares)
#xdisp_width = 10      # Spectrogram *integer* cross-disp. aperture width [px]
xdisp_width_insigma = 10      # Spectrogram cross-disp. aperture width [xdisp_sigma]
# Point-source aperture can be expressed in 'spatial_sigma' (at 1 µm).
# Take it large enough to accomodate most of the flux at all the wavelengths
#aperture_radius = 20          # Point-source spatial aperture radius [spx]
aperture_radius_insigma = 10  # Spatial aperture radius [spatial_sigma]
nramp = 1                # Number of (similar) ramps
