name: Auto Update JSON Config Output For Matlab Compatibility

on:
  push:
    paths:
      - '**/*.toml'
  workflow_dispatch:

jobs:
  generate-parsed-config:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout branch
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install Package
      run: |
        pip install .

    - name: Run JSON script
      run: python scripts/config_to_json.py

    - name: Commit and push to compiled-develop if changed
      if: if: ${github.ref == 'refs/heads/develop'}
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@users.noreply.github.com"

        git fetch origin
        git checkout origin/develop
        git switch -c compiled-develop

        git add src/config_stp/configs/config_stp.json

        # Only commit and push if there are changes
        if git diff --cached --quiet; then
          echo "No changes to commit."
        else
          git commit -m "Auto-update config_stp.json from TOML changes"
          git push --force origin compiled-develop #force in case of merge conflict (someone edited that branch)
        fi
